#! /usr/bin/env python3
# -*- coding: utf-8 -*-
##########################################################################
# NSAp - Copyright (C) CEA, 2023
# Distributed under the terms of the CeCILL-B license, as published by
# the CEA-CNRS-INRIA. Refer to the LICENSE file or to
# http://www.cecill.info/licences/Licence_CeCILL-B_V1-en.html
# for details.
##########################################################################

"""
Organize the analysis steps.
"""

# System import
import fire
import tembedding.workflow as wf


fire.Fire({
    "precompute-dfc-dist": wf.precompute_dfc_dist_exp
})
