#PBS -N Aurel_Test
#PBS -q Nspin_long
#PBS -l nodes=1:ppn=10
#PBS -l mem=64gb
#PBS -l walltime=5:00:00
#PBS -j oe                      
#PBS -o gettingStarted.out

singularity run --bind /neurospin /neurospin/lbi/monkeyfmri/deepstim/workspace/2023_ASM_tembedding/compute_distance/container.sif \
            /neurospin/lbi/monkeyfmri/deepstim/database/ANESTHETIC_database/derivatives/reference_kmeans/inputs/inputs.npy \
            /neurospin/lbi/monkeyfmri/deepstim/database/ANESTHETIC_database/derivatives/reference_kmeans/inputs/metadata.tsv \
            /neurospin/lbi/monkeyfmri/deepstim/workspace/2023_ASM_tembedding/compute_distance/distance_all.npy \
            0
